watchers:
  - name: Link Watcher
    host: ""
    filepath: a/test/testdiff.txt
    lines:
      - startline: 20
        endline: 30
      - startline: 50
        endline: 50
    actions:
      - type: slack
        channel: test-bot
        message: This thing changed!
  - name: Any Line Log Watch
    host: ""
    file_path: a/test/testdiff.txt
    trigger_any_line: true
    actions:
      - type: log
        message: Log Action
        name: Log
      - type: slack
        channel: test-bot
        message: This thing changed!
        name: Post to channel
