version: '3.8'
services:
  mongo:
    image: library/mongo:bionic
    volumes:
      - changelink:/test/db
    environment:
      MONGO_INITDB_DATABASE: changelink
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

volumes:
  link: